// app/api/verify-payment/route.ts (FIXED VERSION)
import { NextResponse } from 'next/server';
import { stripe } from '@/lib/stripe';
import { prisma } from '@/lib/prisma';
import { cookies } from 'next/headers';
import { Prisma } from '@prisma/client';

export async function POST(request: Request) {
  try {
    const { sessionId } = await request.json();
    
    if (!sessionId) {
      return NextResponse.json(
        { error: 'Session ID is required' },
        { status: 400 }
      );
    }

    // Verify session with Stripe
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    
    if (session.payment_status !== 'paid') {
      return NextResponse.json(
        { error: 'Payment not completed' },
        { status: 400 }
      );
    }

    const cookieStore = await cookies();
    const userCookie = cookieStore.get('user')?.value;
    
    if (!userCookie) {
      return NextResponse.json(
        { error: 'Not authenticated' },
        { status: 401 }
      );
    }
    
    const user = JSON.parse(userCookie);

    // Check if order already exists
    const existingOrder = await prisma.order.findUnique({
      where: { stripeSessionId: sessionId },
      include: { items: true }
    });

    let order;
    
    // If order doesn't exist, create it
    if (!existingOrder) {
      const lineItems = await stripe.checkout.sessions.listLineItems(sessionId);
      
      // Calculate totals from Stripe session
      const total = session.amount_total ? session.amount_total / 100 : 0;
      const subtotal = session.amount_subtotal ? session.amount_subtotal / 100 : 0;
      const tax = session.total_details?.amount_tax ? session.total_details.amount_tax / 100 : 0;
      
      const newOrder = await prisma.order.create({
        data: {
          userId: user.id,
          stripeSessionId: sessionId,
          stripeCustomerId: typeof session.customer === 'string' ? session.customer : null,
          // Use correct field names from your schema
          total: total,
          subtotal: subtotal,
          tax: tax,
          shipping: 0, // Default shipping
          discount: 0, // Default discount
          status: 'PAID',
          trackingStatus: 'ORDER_RECEIVED', // Set initial tracking status
          paymentMethod: 'card',
          // Generate order number (will be auto-generated by Prisma with uuid default)
          // customerEmail field doesn't exist in your schema - removed
          items: {
            create: lineItems.data.map((item: any) => ({
              productId: item.price?.product?.metadata?.productId || 'unknown',
              stripePriceId: item.price?.id || '',
              name: item.description || 'Unknown Product',
              price: item.price?.unit_amount ? item.price.unit_amount / 100 : 0,
              quantity: item.quantity || 1,
            }))
          },
          // Set timestamps
          paidAt: new Date(),
          preparingAt: new Date(), // Start preparing immediately
        },
        include: { items: true }
      });
      
      order = newOrder;
      
      // Clear user's cart
      await prisma.cartItem.deleteMany({
        where: {
          cart: {
            userId: user.id
          }
        }
      });
    } else {
      order = existingOrder;
    }

    return NextResponse.json({
      success: true,
      orderId: order.id,
      sessionStatus: session.payment_status,
      orderStatus: order.status
    });

  } catch (error: any) {
    console.error('Error verifying payment:', error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}